version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'nest-payload-test-mongo'
    environment:
      - MONGO_INITDB_DATABASE=payload-nest-site
    volumes:
      - payload-next-mongo-data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: 'nest-payload-test-mongo-express'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=dev123
    depends_on:
      - mongodb
    ports:
      - '8888:8081'

volumes:
  payload-next-mongo-data:
