version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'nest-next-payload-mongo'
    environment:
      - MONGO_INITDB_DATABASE=nest-next-payload
    volumes:
      - nest-next-payload-mongo-data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: 'nest-next-payload-mongo-express'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=dev123
    depends_on:
      - mongodb
    ports:
      - '8888:8081'

volumes:
  nest-next-payload-mongo-data:
